### ISSUE TITLE
Attach pretrained model downloads to release

### ISSUE THREAD

**Issue by gdevenyi** [lab-smile/GRACE#2]
After #1 is complete, please upload and attach to the release the pretrained models instead of relying on external cloud download links that will break.

**Comment by lab-smile** [comment]
The model is too large to be uploaded to Github.


______________________________

Ruogu Fang, Ph.D.  |  Associate Professor  |  Pruitt Family Endowed Fellow

University of Florida | J. Crayton Pruitt Family Department of Biomedical Engineering

Herbert Wertheim College of Engineering

J287 Biomedical Science Building

1275 Center Dr. | Gainesville, FL 32611

•(352) 294-1375 (will forward to cell)

***@***.***

https://lab-smile.github.io<https://lab-smile.github.io/index.html>
________________________________
From: Gabriel A. Devenyi ***@***.***>
Sent: Thursday, February 15, 2024 10:14 AM
To: lab-smile/GRACE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lab-smile/GRACE] Attach pretrained model downloads to release (Issue #2)

[External Email]

After #1<https://github.com/lab-smile/GRACE/issues/1> is complete, please upload and attach to the release the pretrained models instead of relying on external cloud download links that will break.

**Comment by gdevenyi** [comment]
Github release attachments are not commits to a repository, please see
https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas

**Comment by SkylarStolte** [comment]
Hello, please see our release v1.0.0 for an alternative path to our pretrained model.
